### ISSUE TITLE
Contributor's credits

### ISSUE THREAD

**Issue by brunomvsouza** [StudioSol/set#1]
I don't know if the company is obliged to, but I think it is of good taste to give credit to the original contributors when publishing code. Even though the code is old and the person it is not a employee of the company anymore.

**Comment by rodrigo-brito** [comment]
Hi @brunomvsouza,
We included a list of contributors here: [CONTRIBUTORS.md](https://github.com/StudioSol/set/blob/master/CONTRIBUTORS.md)
I tried to use the original commits, but the extraction does not work very well.

The LinkedHashSet library is very useful, I use it a lot in my personal projects. Thank you <3

**Comment by brunovenceslau** [comment]
Hi @rodrigo-brito! Thanks for addressing that.

Nothing but ❤️ to you all there. Cheers 🍻!
